name: Deploy to EC2 Runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy Application
      run: |
        cd ~/express-app
        git pull origin main
        sudo docker stop express-app || true
        sudo docker rm express-app || true
        sudo docker build -t express-app .
        sudo docker run -d -p 3000:3000 --name express-app express-app
